<?php
class Evaluate extends BaseModel{
    public function tableName()
    {
        return '{{evaluate}}';
    }

    /**
     * 属性标签
     */
    public function attributeLabels()
    {
        return array(
            'year' => '学年',
            'sid' => '学号',
            'evaluate1' => '第一学期评语',
            'evaluate2' => '第二学期评语',
        );
    }

    /**
     * 模型验证规则
     */
    public function rules()
    {
        return array(
//            array('evaluate1', 'required', 'message' => '{attribute} 不能为空'),
            array('sid,year,evaluate1,evaluate2','safe')
//            array('evaluate2', 'required', 'message' => '{attribute} 不能为空')
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}