<?php


class Scores extends BaseModel
{
    public function tableName()
    {
        return '{{scores}}';
    }

    public function attributeLabels()
    {
        return array(
            'year' => '学年',
            'subject' => '学科',
            'sid' => '学号',
            'score1' => '第1学期期中成绩',
            'score2' => '第1学期期末成绩',
            'score3' => '第2学期期中成绩',
            'score4' => '第2学期期末成绩'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}