<?php


class Scores extends BaseModel
{
    public function tableName()
    {
        return '{{scores}}';
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}