<?php


class Student extends BaseModel
{
    public function tableName()
    {
        return '{{student}}';
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}